version: "3.7"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - app
    command: /bin/sh -c "nginx -g 'daemon off;'"

networks:
  app:
    driver: bridge
